global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@realpython-recommender.local'
  
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'
    
# 可选：邮件告警配置
# - name: 'email-alert'
#   email_configs:
#   - to: 'admin@example.com'
#     subject: '[Alert] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
#     body: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance'] 